permalink: /:title

_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide 

  column-sizes:
    col-6: One Half
    col-12: Full Width
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: One Half Desktop / Stacked Mobile
    col-4_sm-12: One Third Desktop / Stacked Mobile
    col-3_sm-12: One Quarter Desktop / Stacked Mobile

  image-positions:
    bg-pos-t: Top
    bg-pos-b: Bottom
    bg-pos-l: Left
    bg-pos-r: Right
    bg-pos-center: Center
    bg-pos-tc: Top Center
    bg-pos-tl: Top Left 
    bg-pos-tr: Top Right
    bg-pos-bc: Bottom Center
    bg-pos-bl: Bottom Left
    bg-pos-br: Bottom Right